### ISSUE TITLE
Fix Coveralls setup

### ISSUE THREAD

**Issue by ChristianKuehnel** [open-homeautomation/miflora#56]
There is a Travis CI configuration for Coveralls but it does not yet collect any metrics. This should be fixed.

**Comment by ChristianKuehnel** [comment]
@fuzzmz 
Both are enabled for my fork of the repository. Travis is working, but Coveralls does not show any data. Something must be still wrong in the configuration:
https://travis-ci.org/ChristianKuehnel/miflora
https://coveralls.io/github/ChristianKuehnel/miflora

Do you have any ideas on what the issue might be?

**Comment by fuzzmz** [comment]
Thanks, will take a look at it.

On Oct 21, 2017 09:32, "ChristianKuehnel" <notifications@github.com> wrote:

@fuzzmz <https://github.com/fuzzmz>
Both are enabled for my fork of the repository. Travis is working, but
Coveralls does not show any data. Something must be still wrong in the
configuration:
https://travis-ci.org/ChristianKuehnel/miflora
https://coveralls.io/github/ChristianKuehnel/miflora

Do you have any ideas on what the issue might be?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/open-homeautomation/miflora/issues/56#issuecomment-338368118>,
or mute the thread

**Comment by fuzzmz** [comment]
Work is a bit hectic so I'm not sure I'll be able to look into this any time soon, sorry.

**Comment by Fedalto** [comment]
I can take a look into this
