### ISSUE TITLE
Support for historical data ?

### ISSUE THREAD

**Issue by xavrr** [open-homeautomation/miflora#67]
Hi there,
Thanks for this great work,
It seems like the sensors actually store historical data, any plans to support querying these ?

**Comment by ThomDietrich** [comment]
Yes, in fact there is a by now conflicting PR including this feature, see: https://github.com/open-homeautomation/miflora/pull/27
I believe due to recent developments in this repository the PR was not addressed again till now but now would be a good time to fix the pull request and go forward merging it. @Happyzippy wdyt?

**Comment by xavrr** [comment]
Thanks Thom, I'll have a look to it

**Comment by ChristianKuehnel** [comment]
Implemented here: https://github.com/open-homeautomation/miflora/pull/78
